import fs from "fs";
import path from "path";
import web3 from "../ethereum/web3";
import Head from "next/head";
import Image from "next/image";
import SwapCard from "../components/SwapCard/SwapCard";
import styles from "../styles/Home.module.css";

export default function Home({ conversionRate }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>FaroukSwap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          async
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/semantic-ui@2/dist/semantic.min.css"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://www.linkedin.com/in/farouk-benfraj/" target="_blank">
            FaroukSwap
          </a>
        </h1>
        <SwapCard conversionRate={conversionRate} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps(context) {
  const abiPath = path.resolve(
    process.cwd(),
    "ethereum",
    "contracts",
    "build",
    "ethereum_contracts_FaroukSwap_sol_FaroukSwap.abi"
  );

  const abi = JSON.parse(fs.readFileSync(abiPath));

  const FaroukSwap = new web3.eth.Contract(
    abi,
    "0x671F913Ab9DD24CaA2956bb80901B8f8826D66Ec"
  );

  const conversionRate = await FaroukSwap.methods.conversionRate().call();

  return {
    props: { conversionRate },
  };
}
